### PR TITLE
Release 1.0.4 beta

### PR DESCRIPTION
**Pull request by ometelytsia**
# Version 1.0.4 beta
## Added
- Examples on how to extend the performance toolkit
- Added copy of public User guide into the repo
## Changed
- Refactored report generator
## Fixed
- Hard-coded protocol in jira.jmx file

### CODE REVIEW

**Comment by dagguh** [comment]
How do releases work? Can I roll back to 1.0.3 in case of bugs?

**Comment by ometelytsia** [comment]
> How do releases work? Can I roll back to 1.0.3 in case of bugs?

@dagguh The master branch tracks released code only. All releases are tagged. So if there is a need to roll back to any release:
- `git tag` to get list of all releases
- `git checkout tags/release-name` checkout any particular release version

**Comment by ometelytsia** [comment]
User Guide PR: https://bitbucket.org/atlassian-developers/marketplace/pull-requests/185/update-user-guide-accroding-to-release-104/diff

**Comment by dagguh** [comment]
Oooh, so it's all source-based. I see

**Pull request merged**
