### PR TITLE
Added Type Hints for Selenium UI and Locust IO

### PR DESCRIPTION
**Pull request by craftamap**
The `selenium_ui` package, especially functions of `base_page`, are lacking any python3 type hints. This makes it really cumbersome to implement own selenium tests, as you don't have any support from your ide, such as pycharm or vscode, whatsoever.

This pull request implements those type hints, using the `typing` library of python3.6+.

### CODE REVIEW

**Comment by ometelytsia** [comment]
Hi @craftamap. Thank you for your contribution. We need some time to review your PR and run this branch against our CI.

**Comment by craftamap** [comment]
I also added Type Hints for Locust :)

**Comment by ometelytsia** [comment]
Hey @craftamap. We had an internal meeting with a team to discuss type hints and decided that at the moment we do not want this for the following reasons:
1. It adds extra complexity and reduces readability in some cases like `typing.Dict[str, typing.Union[int, typing.List[typing.Any]]]`
2. Python special constructions like `typing.Any` and `TypeVar('T')` require some theoretical background and python knowledge and may "scary" people to develop app-specific actions with python and selenium.
3. Having types everywhere creates an impression that if you want to extend a toolkit you have to use them, which again a layer of extra complexity for a person with no python experience.

Of course, we understand the helpfulness of type hints, but at the moment (we may reconsider this decision in the future) we decided to give a preference to simplicity.

Thank you again for your contribution and we hope for your understanding.
Oleksandr

**Comment by craftamap** [comment]
Hey Oleksandr,

I understand the decision of your team! I guess it really makes it more complex for people starting out with python :)

Feel free to contact me, if you think about adding them!
I'm gonna close this pr, then. :)

**Pull request closed without merging**
